### ISSUE TITLE
[bug] map only shows UK

### ISSUE THREAD

**Issue by sophiabrandt** [zero-to-mastery/ZtM-Job-Board#2224]
Map only shows a marker on the UK and displays "58 developers...". You cannot drag the marker.

Probably related to last update of dependencies.

**Comment by danagle** [comment]
The source of the issue is the API request in Map.tsx:

https://github.com/zero-to-mastery/ZtM-Job-Board/blob/6bc0af49f02e54492effd58173c6e29ba38642c0/src/components/Map.tsx#L30

This request times out and as a result the data is an empty array to which the special case for the `UK` is added.

https://github.com/zero-to-mastery/ZtM-Job-Board/blob/6bc0af49f02e54492effd58173c6e29ba38642c0/src/components/Map.tsx#L75

**Comment by sophiabrandt** [comment]
Closed via #2249 . Thank you @danagle
