### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Kani712** [zero-to-mastery/ZtM-Job-Board#2531]
I am getting this error. Can someone help to resolve this issue:

remote: Permission to zero-to-mastery/ZtM-Job-Board.git denied to Kani712.
fatal: unable to access 'https://github.com/zero-to-mastery/ZtM-Job-Board.git/': The requested URL returned error: 403

**Comment by shannontorcato** [comment]
@Kani712  When you get a 403 error, it is because you are trying to push your changes to a repository you don't have access to. 

Check your remote with:
`git remote -v`

In my case I get:
![image](https://user-images.githubusercontent.com/44242889/199625132-34d8c78a-4bc3-47a6-97cb-4255ea711974.png)

Check the link below for more details.
[The start here guidelines show how to set up for open source contribution](https://github.com/zero-to-mastery/start-here-guidelines)

**Comment by jorlar** [comment]
I won't say that it's the reason, but try to remove the '/' on the end of the url... just for the fun..
